name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        mode: [debug, release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -mode ${{ matrix.mode }}
